#ifndef _PEANO_HEAP_RECORDS_INTEGERHEAPDATA_H
#define _PEANO_HEAP_RECORDS_INTEGERHEAPDATA_H

#include "peano/utils/Globals.h"
#include "tarch/compiler/CompilerSpecificSettings.h"
#include "peano/utils/PeanoOptimisations.h"
#ifdef Parallel
	#include "tarch/parallel/Node.h"
#endif
#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <complex>
#include <string>
#include <iostream>

namespace peano {
   namespace heap {
      namespace records {
         class IntegerHeapData;
         class IntegerHeapDataPacked;
      }
   }
}

/**
 * @author This class is generated by DaStGen
 * 		   DataStructureGenerator (DaStGen)
 * 		   2007-2009 Wolfgang Eckhardt
 * 		   2012      Tobias Weinzierl
 *
 * 		   build date: 04-02-2014 16:40
 *
 * @date   06/02/2014 21:12
 */
class peano::heap::records::IntegerHeapData { 
   
   public:
      
      typedef peano::heap::records::IntegerHeapDataPacked Packed;
      
      struct PersistentRecords {
         int _u;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const int& u);
         
         /**
          * Generated
          */
          int getU() const ;
         
         /**
          * Generated
          */
          void setU(const int& u) ;
         
         
      };
      
   private: 
      public:

      PersistentRecords _persistentRecords;
      private:

      
   public:
      /**
       * Generated
       */
      IntegerHeapData();
      
      /**
       * Generated
       */
      IntegerHeapData(const PersistentRecords& persistentRecords);
      
      /**
       * Generated
       */
      IntegerHeapData(const int& u);
      
      /**
       * Generated
       */
      ~IntegerHeapData();
      
      /**
       * Generated
       */
       int getU() const ;
      
      /**
       * Generated
       */
       void setU(const int& u) ;
      
      /**
       * Generated
       */
      std::string toString() const;
      
      /**
       * Generated
       */
      void toString(std::ostream& out) const;
      
      
      PersistentRecords getPersistentRecords() const;
      /**
       * Generated
       */
      IntegerHeapDataPacked convert() const;
      
      
   #ifdef Parallel
      protected:
         static tarch::logging::Log _log;
         
         int _senderDestinationRank;
         
      public:
         
         /**
          * Global that represents the mpi datatype.
          * There are two variants: Datatype identifies only those attributes marked with
          * parallelise. FullDatatype instead identifies the whole record with all fields.
          */
         static MPI_Datatype Datatype;
         static MPI_Datatype FullDatatype;
         
         /**
          * Initializes the data type for the mpi operations. Has to be called
          * before the very first send or receive operation is called.
          */
         static void initDatatype();
         
         static void shutdownDatatype();
         
         void send(int destination, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, bool communicateBlocking);
         
         void receive(int source, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, bool communicateBlocking);
         
         static bool isMessageInQueue(int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
         
         int getSenderRank() const;
         
   #endif
      
   };
   
   /**
    * @author This class is generated by DaStGen
    * 		   DataStructureGenerator (DaStGen)
    * 		   2007-2009 Wolfgang Eckhardt
    * 		   2012      Tobias Weinzierl
    *
    * 		   build date: 04-02-2014 16:40
    *
    * @date   06/02/2014 21:12
    */
   class peano::heap::records::IntegerHeapDataPacked { 
      
      public:
         
         struct PersistentRecords {
            int _u;
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const int& u);
            
            /**
             * Generated
             */
             int getU() const ;
            
            /**
             * Generated
             */
             void setU(const int& u) ;
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         IntegerHeapDataPacked();
         
         /**
          * Generated
          */
         IntegerHeapDataPacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         IntegerHeapDataPacked(const int& u);
         
         /**
          * Generated
          */
         ~IntegerHeapDataPacked();
         
         /**
          * Generated
          */
          int getU() const ;
         
         /**
          * Generated
          */
          void setU(const int& u) ;
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         IntegerHeapData convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderDestinationRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             * There are two variants: Datatype identifies only those attributes marked with
             * parallelise. FullDatatype instead identifies the whole record with all fields.
             */
            static MPI_Datatype Datatype;
            static MPI_Datatype FullDatatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, bool communicateBlocking);
            
            void receive(int source, int tag, bool exchangeOnlyAttributesMarkedWithParallelise, bool communicateBlocking);
            
            static bool isMessageInQueue(int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      #endif
      
